# The representation of SMPL search & planning data during a request
float64 start_IK_compute_time
float64 restoration_time
float64 search_time
float64 path_extraction_time
float64 shortcut_time
float64 interpolation_time
float64 planning_time
int64 num_expansions
int64 cost
int64 epsilon
int64 restoration_step
int64 path_num_states
int64 original_waypoints
int64 interpolation_waypoints
int64 shortcut_waypoints
ActionState[] action_states
SolutionState[] solution_states


